---
- name: Inicializar Docker Swarm no nó manager
  hosts: manager
  become: true
  tasks:

    - name: Inicializar Swarm caso não esteja ativo
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
