---
- name: Remover Portainer do Docker Swarm
  hosts: manager
  become: true
  tasks:
    - name: Importar tasks para desinstalar o Portainer
      ansible.builtin.import_tasks: tasks/uninstall-portainer.ansible.yml
