- name: Remover pacotes Docker antigos e conflitantes
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
      - runc
    state: absent

- name: Instalar dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Adicionar repositório oficial do Docker
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Instalar Docker e plugins necessários
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Habilitar e iniciar o serviço Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Testar instalação do Docker com hello-world
  ansible.builtin.command: docker run hello-world
  register: docker_test
  changed_when: false

- name: Exibir resultado do teste
  ansible.builtin.debug:
    msg: "{{ docker_test.stdout }}"
