- name: Obter Token para Join dos Workers
  ansible.builtin.command: docker swarm join-token worker -q
  delegate_to: 192.168.56.4
  register: worker_token
  changed_when: false

- name: Adicionar Workers ao Swarm
  ansible.builtin.command: docker swarm join --token {{ worker_token.stdout }} 192.168.56.4:2377
  args:
    creates: /var/lib/docker/swarm/worker
  when: worker_token.stdout != ""
