VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/rocky9"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 8192
    v.cpus = 4
    v.linked_clone = true
  end

  config.vm.define "app1" do |app|
    app.vm.hostname = "app1.test"
    app.vm.network :private_network, ip: "192.168.56.4"
  end

  config.vm.define "app2" do |app|
    app.vm.hostname = "app2.test"
    app.vm.network :private_network, ip: "192.168.56.5"
  end

  config.vm.define "app3" do |app|
    app.vm.hostname = "app3.test"
    app.vm.network :private_network, ip: "192.168.56.6"
  end
end
