- name: Transferir e Deployar aplicação no Docker Swarm
  hosts: manager
  become: true
  vars:
    stack_name: "app"
    stack_file: "/home/vagrant/app.stack.yml"
    nfs_server_ip: "{{ inventory_hostname }}"
  tasks:
    - name: Gerar e copiar `app.stack.yml` diretamente para o nó Manager
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/app.stack.yml.j2"
        dest: "{{ stack_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Fazer deploy do stack no Docker Swarm
      community.docker.docker_stack:
        state: present
        name: "{{ stack_name }}"
        compose:
          - "{{ stack_file }}"
      register: deploy_output

    - name: Exibir resultado do deploy
      ansible.builtin.debug:
        var: deploy_output.stdout_lines
