---
- hosts: all
  become: yes
  vars_files:
    - vars/redis.yml
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.redis
    - linux-system-roles.selinux
  vars:
    firewall_allowed_tcp_ports:
      - 22
      - "{{ redis_port }}"
    firewall_default_zone: public

  tasks:
    - name: Configure SELinux to disabled
      ansible.posix.selinux:
        policy: targeted
        state: disabled
      register: selinux_status

    - name: Reboot the system if SELinux was set to disabled
      ansible.builtin.reboot:
        msg: "Rebooting after disabling SELinux"
      when: selinux_status is changed

    - name: Open ports in the firewall
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        zone: "{{ firewall_default_zone }}"
        permanent: yes
        state: enabled
      loop: "{{ firewall_allowed_tcp_ports }}"

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      when: firewall_allowed_tcp_ports is defined
