version: '3.8'

services:
  minha_aplicacao:
    image: minha_aplicacao:latest
    deploy:
      replicas: 2  # Define quantas instâncias do serviço serão executadas
      restart_policy:
        condition: on-failure
    volumes:
      - nfs_download:/download
      - nfs_var_upload:/var/upload
      - nfs_eproc_tmp:/var/www/eproc_tmp
    networks:
      - app_network
    ports:
      - "8080:80"  # Ajuste conforme necessário

volumes:
  nfs_download:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr={{ groups['manager'][0] }},rw"
      device: ":/srv/nfs/share/download"

  nfs_var_upload:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr={{ groups['manager'][0] }},rw"
      device: ":/srv/nfs/share/var_upload"

  nfs_eproc_tmp:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr={{ groups['manager'][0] }},rw"
      device: ":/srv/nfs/share/eproc_tmp"

networks:
  app_network:
    driver: overlay
